name: core_platform
version: "2.1.0"
config-version: 2

profile: "snowflake"
require-dbt-version: ">=1.6.0"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  truncate_timespan_to: "{{ current_timestamp() }}"

models:
  core_platform:
    staging:
      +required_tests: {"unique.*|not_null": 1}
      +materialized: view
    marts:
      +materialized: table
flags:
  require_generic_test_arguments_property: true